[package]
name = "column-rs"
version = "0.15.1"
edition = "2021"

[lib]
name = "column_rs"
path = "src/lib.rs"

[[bin]]
name = "column-rs"
path = "src/bin/column-rs/main.rs"

[dependencies]
rayon = "1"
db-storage = { git = "https://github.com/t-rust-db/db-storage", tag = "v0.1.0" }
sql-types = { git = "https://github.com/t-rust-db/db-core", tag = "v0.1.0", package = "sql-types" }
sql-expr = { git = "https://github.com/t-rust-db/db-core", tag = "v0.1.0", package = "sql-expr" }
sql-parser = { git = "https://github.com/t-rust-db/db-core", tag = "v0.1.0", package = "sql-parser" }
db-parquet = { git = "https://github.com/t-rust-db/db-parquet", tag = "v0.1.0" }
db-cli = { git = "https://github.com/t-rust-db/db-cli", tag = "v0.1.0" }
