[package]
name = "column-rs"
version = "0.20.1"
edition = "2021"

[lib]
name = "column_rs"
path = "src/lib.rs"

[[bin]]
name = "column-rs"
path = "src/bin/column-rs/main.rs"

[dependencies]
db-core = { git = "https://github.com/t-rust-db/db-core", tag = "v0.78.1", default-features = false, features = ["parser-column", "vm-batch", "codegen-batch", "emit-batch", "storage-column"] }
db-cli = { git = "https://github.com/t-rust-db/db-cli", tag = "v0.4.1" }
