[package]
name = "column-rs"
version = "0.18.0"
edition = "2021"

[lib]
name = "column_rs"
path = "src/lib.rs"

[[bin]]
name = "column-rs"
path = "src/bin/column-rs/main.rs"

[dependencies]
db-storage = { git = "https://github.com/t-rust-db/db-storage", tag = "v0.4.1" }
db-core = { git = "https://github.com/t-rust-db/db-core", tag = "v0.60.0", default-features = false, features = ["parser-column", "vm-batch", "codegen-batch", "emit-batch"] }
db-cli = { git = "https://github.com/t-rust-db/db-cli", tag = "v0.3.0" }
