#!/usr/bin/env bash
# Regenerate the DuckDB oracle fixtures used by tests/oracle.rs.
#
# Pinned DuckDB version: v1.5.5 (Variegata) — CI installs this exact
# version so oracle comparisons stay reproducible.
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

duckdb -c "
COPY (SELECT i AS id FROM range(1, 1001) t(i))
TO 'int64.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (SELECT (i * 1.5)::DOUBLE AS val FROM range(1, 1001) t(i))
TO 'double.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (SELECT (i % 2 = 0) AS flag FROM range(1, 1001) t(i))
TO 'boolean.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (SELECT 'row_' || i AS name FROM range(1, 1001) t(i))
TO 'string.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (
  SELECT i AS id, (i * 1.5)::DOUBLE AS val, (i % 2 = 0) AS flag, 'row_' || i AS name
  FROM range(1, 1001) t(i)
) TO 'mixed.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (
  SELECT
    CASE WHEN i % 7 = 0 THEN NULL ELSE i END AS id,
    CASE WHEN i % 5 = 0 THEN NULL ELSE (i * 1.5)::DOUBLE END AS val,
    CASE WHEN i % 3 = 0 THEN NULL ELSE (i % 2 = 0) END AS flag,
    CASE WHEN i % 11 = 0 THEN NULL ELSE 'row_' || i END AS name
  FROM range(1, 1001) t(i)
) TO 'nullable.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (
  SELECT ['north', 'south', 'east', 'west'][(i % 4) + 1] AS region
  FROM range(1, 1001) t(i)
) TO 'region.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (SELECT i AS id FROM range(1, 1001) t(i))
TO 'delta.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED, PARQUET_VERSION V2);
"

duckdb -c "
COPY (SELECT i AS id, (i * 1.5)::DOUBLE AS val, 'row_' || i AS name FROM range(1, 2001) t(i))
TO 'snappy.parquet' (FORMAT PARQUET, COMPRESSION SNAPPY);
"

duckdb -c "
COPY (SELECT i AS id, (i * 1.5)::DOUBLE AS val, 'row_' || i AS name FROM range(1, 2001) t(i))
TO 'zstd.parquet' (FORMAT PARQUET, COMPRESSION ZSTD);
"

duckdb -c "
COPY (
  SELECT (['east','west','north','south'])[1 + (i % 4)] AS region, (i * 2.5)::DOUBLE AS amount, i AS id
  FROM range(1, 5001) t(i)
) TO 'production.parquet' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 1000);
"

duckdb -c "
COPY (
  SELECT
    (i)::TINYINT AS i8,
    (i * 1000)::INTEGER AS i32,
    (i * 1.5)::FLOAT AS f32,
    (i * 1.23)::DECIMAL(38,10) AS dec_big
  FROM range(0, 100) t(i)
) TO 'dtypes.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (
  SELECT i AS id, CASE WHEN i = 21 THEN 'south' ELSE (['east','west','north'])[1+(i%3)] END AS region_key
  FROM range(1, 22) t(i)
) TO 'orders.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
COPY (SELECT (['east','west','north'])[1+i] AS key, (i*100)::DOUBLE AS budget FROM range(0, 3) t(i))
TO 'regions.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

duckdb -c "
COPY (
  SELECT
    (TIMESTAMP '2024-01-15 10:30:00' + INTERVAL (i) SECOND) AS ts_us,
    (i * 1.23)::DECIMAL(10,2) AS dec_small,
    (i * 1.23456789)::DECIMAL(38,10) AS dec_big
  FROM range(0, 10) t(i)
) TO 'logical_types.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
COPY (SELECT (TIMESTAMP '2024-01-15 10:30:00' + INTERVAL (i) SECOND)::TIMESTAMP_MS AS ts_ms FROM range(0, 5) t(i))
TO 'logical_types_millis.parquet' (FORMAT PARQUET, COMPRESSION UNCOMPRESSED);
"

echo "Fixtures written to $DIR"
echo "Note: the 100K+ row fixture used by the large-file oracle test is"
echo "generated on the fly by tests/oracle.rs (not checked into git)."
echo
echo "multipage.parquet is NOT regenerated by this script -- DuckDB always"
echo "writes a column chunk's entire row group into a single DATA_PAGE"
echo "regardless of size, so it can't reproduce a multi-page chunk. It was"
echo "generated once with pyarrow instead (requires 'pip install pyarrow'):"
echo
cat <<'PYEOF'
python3 -c "
import pyarrow as pa, pyarrow.parquet as pq
n = 5000
table = pa.table({
    'id': pa.array(range(1, n + 1), type=pa.int64()),
    'name': pa.array([f'row_{i}_' + 'x' * (i % 50) for i in range(1, n + 1)]),
})
pq.write_table(table, 'multipage.parquet', compression='none',
               data_page_size=2048, row_group_size=n, use_dictionary=True)
"
PYEOF
echo
echo "nested.parquet, list.parquet, and map.parquet are also NOT regenerated"
echo "by this script -- DuckDB can't produce nested (struct/list/map) Parquet"
echo "schemas either. Generated once with pyarrow, with use_dictionary=False"
echo "since the nested-column reader (src/nested.rs) only supports PLAIN"
echo "encoding for nested/repeated leaves so far (see #89):"
echo
cat <<'PYEOF'
python3 -c "
import pyarrow as pa, pyarrow.parquet as pq
table = pa.table({
    'id': pa.array(range(10), type=pa.int64()),
    'point': pa.array([{'x': i, 'y': i * 2} for i in range(10)],
                       type=pa.struct([('x', pa.int64()), ('y', pa.int64())])),
})
pq.write_table(table, 'nested.parquet', compression='none', use_dictionary=False)

lists = pa.table({
    'numbers': pa.array([[1, 2, 3], [], [4]], type=pa.list_(pa.int64())),
    'letters': pa.array([['a', 'b'], ['c'], None], type=pa.list_(pa.string())),
})
pq.write_table(lists, 'list.parquet', compression='none', use_dictionary=False)

maps = pa.table({
    'kv': pa.array([{'a': 1, 'b': 2}, {}, {'c': 3}], type=pa.map_(pa.string(), pa.int64())),
})
pq.write_table(maps, 'map.parquet', compression='none', use_dictionary=False)
"
PYEOF
echo
echo "int96_timestamps.parquet is also NOT regenerated by this script --"
echo "DuckDB has no option to write legacy INT96 timestamps. Generated once"
echo "with pyarrow (dictionary-encoded by default -- exercises the INT96"
echo "dictionary decode path too):"
echo
cat <<'PYEOF'
python3 -c "
import pyarrow as pa, pyarrow.parquet as pq, datetime
table = pa.table({
    'ts': pa.array([datetime.datetime(2024,1,15,10,30,0) + datetime.timedelta(seconds=i) for i in range(5)],
                   type=pa.timestamp('us')),
})
pq.write_table(table, 'int96_timestamps.parquet', compression='none', use_deprecated_int96_timestamps=True)
"
PYEOF
