//! Compile a SQL query to native Rust source (#98). Two shapes:
//!
//! - Flat/`GROUP BY`/`ORDER BY`/`LIMIT` queries (#101) compile to a `const
//!   PROGRAM: &[Opcode]` -- no runtime SQL parsing, no dynamic dispatch,
//!   the query plan is baked into the binary as data.
//! - `JOIN` and `IN (SELECT ...)` semi-joins (#103) bypass the VM program
//!   entirely at runtime too (`execute_joined`/`execute_semi_join`
//!   materialize whole tables and hash-join in plain Rust), so there's no
//!   single `Opcode` array to emit for them. Instead, codegen reconstructs
//!   the parsed `Query` as a literal Rust value -- built from `String`/
//!   `Vec` constructors, not `const`, but still no SQL *text* parsed at
//!   runtime -- and calls `execute_joined`/`execute_semi_join` with it.
//!
//! Window functions (`execute_windowed`) aren't supported by either shape
//! yet; `generate` returns [`CodegenError::Unsupported`] for those.

use crate::query::{self, output_column_names, AggPart};
use crate::sql::{self, AggFunc, BinOp, Expr, Join, JoinKind, Literal, OrderBy, ParseError, Query, SelectItem};
use crate::vm::{MapOp, Opcode, Value};
use std::fmt::Write as _;

#[derive(Debug)]
pub enum CodegenError {
    Parse(ParseError),
    Unsupported(&'static str),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::Parse(e) => write!(f, "{e}"),
            CodegenError::Unsupported(what) => write!(f, "codegen does not support {what} yet"),
        }
    }
}

impl std::error::Error for CodegenError {}

impl From<ParseError> for CodegenError {
    fn from(e: ParseError) -> Self {
        CodegenError::Parse(e)
    }
}

pub type Result<T> = std::result::Result<T, CodegenError>;

/// Compile `sql_text` into a standalone `.rs` source file: `const PROGRAM`
/// (the compiled VM program), `const COLUMNS_TO_LOAD`/`const COLUMNS` (the
/// input/output column names), and a `main` that reads every Parquet file
/// path given on the command line, runs `PROGRAM` against each, and prints
/// the results.
pub fn generate(sql_text: &str) -> Result<String> {
    let query = sql::parse(sql_text)?;
    if query.columns.iter().any(|c| matches!(c, SelectItem::Window(_))) {
        return Err(CodegenError::Unsupported("window functions"));
    }

    if !query.joins.is_empty() {
        if query.joins.len() > 1 {
            return Err(CodegenError::Unsupported("more than one JOIN"));
        }
        return Ok(render_joined(sql_text, &query));
    }
    if let Some(Expr::InSubquery { expr, subquery }) = &query.where_clause {
        let Expr::Column(_) = expr.as_ref() else {
            return Err(CodegenError::Unsupported("IN (SELECT ...) with a non-column left-hand side"));
        };
        return Ok(render_semi_join(sql_text, &query, subquery));
    }

    let plan = query::compile(&query);
    let columns = output_column_names(&query);
    Ok(render(sql_text, &query.from, &plan.columns_to_load, &plan.program, &columns, &plan.agg_parts, plan.num_group_keys, plan.order_by, plan.limit))
}

#[allow(clippy::too_many_arguments)]
fn render(
    sql_text: &str,
    table: &str,
    columns_to_load: &[String],
    program: &[Opcode],
    columns: &[String],
    agg_parts: &[AggPart],
    num_group_keys: usize,
    order_by: Option<(usize, bool)>,
    limit: Option<usize>,
) -> String {
    let mut out = String::new();
    let version = env!("CARGO_PKG_VERSION");
    let _ = writeln!(out, "//! Generated by column-rs codegen v{version} -- DO NOT EDIT");
    let _ = writeln!(out, "//! Query: {}", sql_text.replace('\n', " "));
    let _ = writeln!(out, "//! Table: {table}");
    out.push_str("#![forbid(unsafe_code)]\n\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str("use column_rs::file::ParquetFile;\n");
    out.push_str("use column_rs::query::AggPart;\n");
    out.push_str("use column_rs::sql::AggFunc;\n");
    out.push_str("use column_rs::vm::{MapOp, Opcode, Value};\n\n");

    out.push_str("const PROGRAM: &[Opcode] = &[\n");
    for op in program {
        let _ = writeln!(out, "    {},", render_opcode(op));
    }
    out.push_str("];\n\n");

    out.push_str("const COLUMNS_TO_LOAD: &[&str] = &[");
    for name in columns_to_load {
        let _ = write!(out, "{}, ", rust_str_literal(name));
    }
    out.push_str("];\n\n");

    out.push_str("const COLUMNS: &[&str] = &[");
    for name in columns {
        let _ = write!(out, "{}, ", rust_str_literal(name));
    }
    out.push_str("];\n\n");

    out.push_str("const AGG_PARTS: &[AggPart] = &[");
    for part in agg_parts {
        let _ = write!(out, "{}, ", render_agg_part(part));
    }
    out.push_str("];\n\n");

    let _ = writeln!(out, "const NUM_GROUP_KEYS: usize = {num_group_keys};");
    let _ = writeln!(out, "const ORDER_BY: Option<(usize, bool)> = {};", render_order_by(order_by));
    let _ = writeln!(out, "const LIMIT: Option<usize> = {};\n", render_option_usize(limit));

    out.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");
    out.push_str("    let args: Vec<_> = std::env::args().skip(1).collect();\n");
    out.push_str("    if args.is_empty() {\n");
    out.push_str("        eprintln!(\"usage: {} <file.parquet>...\", std::env::args().next().unwrap_or_default());\n");
    out.push_str("        std::process::exit(1);\n");
    out.push_str("    }\n\n");
    out.push_str("    println!(\"{}\", COLUMNS.join(\"\\t\"));\n");
    out.push_str("    for pattern in &args {\n");
    out.push_str("    for path in expand_path(pattern) {\n");
    out.push_str("        let data = std::fs::read(&path)?;\n");
    out.push_str("        let file = ParquetFile::open(&data)?;\n");
    out.push_str("        let rows = column_rs::query::run_program(&file, COLUMNS_TO_LOAD, PROGRAM)?;\n");
    out.push_str("        let rows = column_rs::query::post_process(AGG_PARTS, NUM_GROUP_KEYS, ORDER_BY, LIMIT, rows);\n");
    out.push_str("        for row in rows {\n");
    out.push_str("            let line: Vec<String> = row.iter().map(|v| v.to_string()).collect();\n");
    out.push_str("            println!(\"{}\", line.join(\"\\t\"));\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");
    out.push_str(EXPAND_PATH_HELPER);
    out
}

/// A path or a simple `*`-glob (one wildcard, in the file name only --
/// e.g. `data/*.parquet`) expanded against the filesystem, sorted for
/// deterministic output. A literal path with no `*` is returned as-is
/// without touching the filesystem, so a nonexistent literal path still
/// surfaces its read error normally rather than silently expanding to
/// nothing.
const EXPAND_PATH_HELPER: &str = r#"fn expand_path(pattern: &str) -> Vec<std::path::PathBuf> {
    if !pattern.contains('*') {
        return vec![std::path::PathBuf::from(pattern)];
    }
    let path = std::path::Path::new(pattern);
    let dir = path.parent().filter(|p| !p.as_os_str().is_empty()).unwrap_or_else(|| std::path::Path::new("."));
    let file_pattern = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
    let (prefix, suffix) = file_pattern.split_once('*').unwrap_or((file_pattern, ""));
    let mut matches: Vec<_> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.file_name().and_then(|n| n.to_str()).is_some_and(|n| n.starts_with(prefix) && n.ends_with(suffix) && n.len() >= prefix.len() + suffix.len()))
        .collect();
    matches.sort();
    matches
}
"#;

fn render_agg_part(part: &AggPart) -> String {
    match part {
        AggPart::GroupKey => "AggPart::GroupKey".to_string(),
        AggPart::Sum => "AggPart::Sum".to_string(),
        AggPart::Count => "AggPart::Count".to_string(),
        AggPart::Min => "AggPart::Min".to_string(),
        AggPart::Max => "AggPart::Max".to_string(),
        AggPart::Avg(sum, count) => format!("AggPart::Avg({sum}, {count})"),
    }
}

fn render_order_by(order_by: Option<(usize, bool)>) -> String {
    match order_by {
        Some((pos, desc)) => format!("Some(({pos}, {desc}))"),
        None => "None".to_string(),
    }
}

/// Render a `JOIN` query: a `main()` that opens the two named tables
/// (matched to `query.from`/`join.table` by file stem, like
/// [`crate::query::QueryEngine`]), reconstructs `query` as a literal
/// `Query` value (built at runtime via ordinary `Vec`/`String`
/// constructors, not parsed from SQL text), and calls
/// [`crate::query::execute_joined`].
fn render_joined(sql_text: &str, query: &Query) -> String {
    let other_table = query.joins[0].table.clone();
    render_multi_table(sql_text, query, &other_table, "execute_joined")
}

/// Render an `IN (SELECT ...)` semi-join query the same way as
/// [`render_joined`], but calling [`crate::query::execute_semi_join`] with
/// the subquery's table as the second table.
fn render_semi_join(sql_text: &str, query: &Query, subquery: &Query) -> String {
    render_multi_table(sql_text, query, &subquery.from, "execute_semi_join")
}

fn render_multi_table(sql_text: &str, query: &Query, other_table: &str, exec_fn: &str) -> String {
    let columns = output_column_names(query);
    let mut out = String::new();
    let version = env!("CARGO_PKG_VERSION");
    let _ = writeln!(out, "//! Generated by column-rs codegen v{version} -- DO NOT EDIT");
    let _ = writeln!(out, "//! Query: {}", sql_text.replace('\n', " "));
    let _ = writeln!(out, "//! Tables: {}, {other_table}", query.from);
    out.push_str("#![forbid(unsafe_code)]\n\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str("use column_rs::file::ParquetFile;\n");
    out.push_str("use column_rs::sql::{AggFunc, BinOp, Expr, Join, JoinKind, Literal, OrderBy, Query, SelectItem};\n\n");

    out.push_str("const COLUMNS: &[&str] = &[");
    for name in &columns {
        let _ = write!(out, "{}, ", rust_str_literal(name));
    }
    out.push_str("];\n\n");

    let _ = writeln!(out, "const MAIN_TABLE: &str = {};", rust_str_literal(&query.from));
    let _ = writeln!(out, "const OTHER_TABLE: &str = {};\n", rust_str_literal(other_table));

    let _ = writeln!(out, "fn build_query() -> Query {{\n    {}\n}}\n", render_query(query));

    out.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");
    out.push_str("    let args: Vec<_> = std::env::args().skip(1).collect();\n");
    out.push_str("    if args.is_empty() {\n");
    out.push_str("        eprintln!(\"usage: {} <file-or-glob>... (must cover tables '{}' and '{}')\", std::env::args().next().unwrap_or_default(), MAIN_TABLE, OTHER_TABLE);\n");
    out.push_str("        std::process::exit(1);\n");
    out.push_str("    }\n\n");
    out.push_str("    let mut tables: std::collections::HashMap<String, std::path::PathBuf> = std::collections::HashMap::new();\n");
    out.push_str("    for pattern in &args {\n");
    out.push_str("        for path in expand_path(pattern) {\n");
    out.push_str("            let name = path.file_stem().and_then(|s| s.to_str()).unwrap_or(\"data\").to_string();\n");
    out.push_str("            tables.insert(name, path);\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    let main_path = tables.get(MAIN_TABLE).ok_or_else(|| format!(\"no file given for table '{MAIN_TABLE}'\"))?;\n");
    out.push_str("    let other_path = tables.get(OTHER_TABLE).ok_or_else(|| format!(\"no file given for table '{OTHER_TABLE}'\"))?;\n");
    out.push_str("    let main_data = std::fs::read(main_path)?;\n");
    out.push_str("    let other_data = std::fs::read(other_path)?;\n");
    out.push_str("    let main_file = ParquetFile::open(&main_data)?;\n");
    out.push_str("    let other_file = ParquetFile::open(&other_data)?;\n");
    out.push_str("    let query = build_query();\n");
    let _ = writeln!(out, "    let rows = column_rs::query::{exec_fn}(&main_file, &other_file, &query)?;");
    out.push_str("    println!(\"{}\", COLUMNS.join(\"\\t\"));\n");
    out.push_str("    for row in rows {\n");
    out.push_str("        let line: Vec<String> = row.iter().map(|v| v.to_string()).collect();\n");
    out.push_str("        println!(\"{}\", line.join(\"\\t\"));\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");
    out.push_str(EXPAND_PATH_HELPER);
    out
}

fn render_query(query: &Query) -> String {
    let columns: Vec<String> = query.columns.iter().map(render_select_item).collect();
    let joins: Vec<String> = query.joins.iter().map(render_join).collect();
    let group_by: Vec<String> = query.group_by.iter().map(|c| format!("{}.to_string()", rust_str_literal(c))).collect();
    format!(
        "Query {{ columns: vec![{}], from: {}.to_string(), joins: vec![{}], where_clause: {}, group_by: vec![{}], order_by: {}, limit: {} }}",
        columns.join(", "),
        rust_str_literal(&query.from),
        joins.join(", "),
        render_option_expr(query.where_clause.as_ref()),
        group_by.join(", "),
        render_option_order_by(query.order_by.as_ref()),
        render_option_usize(query.limit),
    )
}

fn render_select_item(item: &SelectItem) -> String {
    match item {
        SelectItem::Column(name) => format!("SelectItem::Column({}.to_string())", rust_str_literal(name)),
        SelectItem::Agg(func, arg) => format!("SelectItem::Agg(AggFunc::{}, {})", render_agg_func(*func), render_option_string(arg.as_deref())),
        SelectItem::Window(_) => unreachable!("window functions are rejected before reaching codegen"),
    }
}

fn render_option_string(s: Option<&str>) -> String {
    match s {
        Some(s) => format!("Some({}.to_string())", rust_str_literal(s)),
        None => "None".to_string(),
    }
}

fn render_join(join: &Join) -> String {
    let kind = match join.kind {
        JoinKind::Inner => "Inner",
        JoinKind::Left => "Left",
    };
    format!(
        "Join {{ kind: JoinKind::{kind}, table: {}.to_string(), left_col: {}.to_string(), right_col: {}.to_string() }}",
        rust_str_literal(&join.table),
        rust_str_literal(&join.left_col),
        rust_str_literal(&join.right_col),
    )
}

fn render_expr(expr: &Expr) -> String {
    match expr {
        Expr::Column(name) => format!("Expr::Column({}.to_string())", rust_str_literal(name)),
        Expr::Literal(lit) => format!("Expr::Literal({})", render_literal(lit)),
        Expr::BinaryOp(l, op, r) => format!("Expr::BinaryOp(Box::new({}), BinOp::{}, Box::new({}))", render_expr(l), render_bin_op(*op), render_expr(r)),
        Expr::InSubquery { expr, subquery } => format!("Expr::InSubquery {{ expr: Box::new({}), subquery: Box::new({}) }}", render_expr(expr), render_query(subquery)),
    }
}

fn render_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(v) => format!("Literal::Int({v})"),
        Literal::Float(v) => format!("Literal::Float({v:?})"),
        Literal::Str(v) => format!("Literal::Str({}.to_string())", rust_str_literal(v)),
    }
}

fn render_bin_op(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "Add",
        BinOp::Sub => "Sub",
        BinOp::Mul => "Mul",
        BinOp::Div => "Div",
        BinOp::Eq => "Eq",
        BinOp::Ne => "Ne",
        BinOp::Lt => "Lt",
        BinOp::Le => "Le",
        BinOp::Gt => "Gt",
        BinOp::Ge => "Ge",
        BinOp::And => "And",
        BinOp::Or => "Or",
    }
}

fn render_option_expr(expr: Option<&Expr>) -> String {
    match expr {
        Some(e) => format!("Some({})", render_expr(e)),
        None => "None".to_string(),
    }
}

fn render_option_order_by(ob: Option<&OrderBy>) -> String {
    match ob {
        Some(OrderBy { column, descending }) => format!("Some(OrderBy {{ column: {}.to_string(), descending: {descending} }})", rust_str_literal(column)),
        None => "None".to_string(),
    }
}

fn render_opcode(op: &Opcode) -> String {
    match op {
        Opcode::LoadColumn { reg, column } => format!("Opcode::LoadColumn {{ reg: {reg}, column: std::borrow::Cow::Borrowed({}) }}", rust_str_literal(column)),
        Opcode::LoadConst { reg, value } => format!("Opcode::LoadConst {{ reg: {reg}, value: {} }}", render_value(value)),
        Opcode::Map { dst, op, a, b } => format!("Opcode::Map {{ dst: {dst}, op: MapOp::{}, a: {a}, b: {b} }}", render_map_op(*op)),
        Opcode::Filter { predicate } => format!("Opcode::Filter {{ predicate: {predicate} }}"),
        Opcode::Reduce { func, src, dst } => format!("Opcode::Reduce {{ func: AggFunc::{}, src: {}, dst: {dst} }}", render_agg_func(*func), render_option_usize(*src)),
        Opcode::GroupReduce { group_by, aggs, agg_dst } => {
            let group_by = render_usize_slice(group_by);
            let agg_dst = render_usize_slice(agg_dst);
            let aggs: Vec<String> = aggs.iter().map(|(f, s)| format!("(AggFunc::{}, {})", render_agg_func(*f), render_option_usize(*s))).collect();
            format!("Opcode::GroupReduce {{ group_by: std::borrow::Cow::Borrowed(&{group_by}), aggs: std::borrow::Cow::Borrowed(&[{}]), agg_dst: std::borrow::Cow::Borrowed(&{agg_dst}) }}", aggs.join(", "))
        }
        Opcode::Scan => "Opcode::Scan".to_string(),
        Opcode::Emit { registers } => format!("Opcode::Emit {{ registers: std::borrow::Cow::Borrowed(&{}) }}", render_usize_slice(registers)),
        Opcode::NextSegment { loop_start } => format!("Opcode::NextSegment {{ loop_start: {loop_start} }}"),
        Opcode::Halt => "Opcode::Halt".to_string(),
    }
}

fn render_usize_slice(values: &[usize]) -> String {
    format!("[{}]", values.iter().map(usize::to_string).collect::<Vec<_>>().join(", "))
}

fn render_option_usize(v: Option<usize>) -> String {
    match v {
        Some(r) => format!("Some({r})"),
        None => "None".to_string(),
    }
}

fn render_map_op(op: MapOp) -> &'static str {
    match op {
        MapOp::Add => "Add",
        MapOp::Sub => "Sub",
        MapOp::Mul => "Mul",
        MapOp::Div => "Div",
        MapOp::Eq => "Eq",
        MapOp::Ne => "Ne",
        MapOp::Lt => "Lt",
        MapOp::Le => "Le",
        MapOp::Gt => "Gt",
        MapOp::Ge => "Ge",
        MapOp::And => "And",
        MapOp::Or => "Or",
    }
}

fn render_agg_func(func: AggFunc) -> &'static str {
    match func {
        AggFunc::Count => "Count",
        AggFunc::Sum => "Sum",
        AggFunc::Avg => "Avg",
        AggFunc::Min => "Min",
        AggFunc::Max => "Max",
    }
}

fn render_value(value: &Value) -> String {
    match value {
        Value::Int(v) => format!("Value::Int({v})"),
        Value::Float(v) => format!("Value::Float({v:?})"),
        Value::Bool(v) => format!("Value::Bool({v})"),
        Value::Str(v) => format!("Value::Str(std::borrow::Cow::Borrowed({}))", rust_str_literal(v)),
        Value::Null => "Value::Null".to_string(),
    }
}

/// Render `s` as a Rust string literal, escaping characters that would
/// otherwise break out of it.
fn rust_str_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_const_program_for_a_flat_filter_query() {
        let src = generate("SELECT id, amount FROM events WHERE amount > 100").unwrap();
        assert!(src.contains("const PROGRAM: &[Opcode] = &["), "{src}");
        assert!(src.contains("const COLUMNS_TO_LOAD: &[&str] ="), "{src}");
        assert!(src.contains("\"id\"") && src.contains("\"amount\""), "{src}");
        assert!(src.contains("const COLUMNS: &[&str] = &[\"id\", \"amount\", ];"), "{src}");
        assert!(src.contains("#![forbid(unsafe_code)]"));
        assert!(src.contains("fn main()"));
    }

    #[test]
    fn generated_main_supports_glob_expansion() {
        let src = generate("SELECT id FROM t").unwrap();
        assert!(src.contains("fn expand_path"), "{src}");
        assert!(src.contains("for path in expand_path(pattern)"), "{src}");
    }

    #[test]
    fn generates_query_literal_for_join() {
        let src = generate("SELECT a.id, b.budget FROM a JOIN b ON a.id = b.id").unwrap();
        assert!(src.contains("fn build_query() -> Query"), "{src}");
        assert!(src.contains("execute_joined(&main_file, &other_file, &query)"), "{src}");
        assert!(src.contains("const MAIN_TABLE: &str = \"a\";"), "{src}");
        assert!(src.contains("const OTHER_TABLE: &str = \"b\";"), "{src}");
        assert!(src.contains("JoinKind::Inner"), "{src}");
    }

    #[test]
    fn generates_query_literal_for_semi_join() {
        let src = generate("SELECT id FROM orders WHERE region_key IN (SELECT key FROM regions)").unwrap();
        assert!(src.contains("execute_semi_join(&main_file, &other_file, &query)"), "{src}");
        assert!(src.contains("const OTHER_TABLE: &str = \"regions\";"), "{src}");
        assert!(src.contains("Expr::InSubquery"), "{src}");
    }

    #[test]
    fn rejects_more_than_one_join() {
        let err = generate("SELECT a.id FROM a JOIN b ON a.id = b.id JOIN c ON a.id = c.id").unwrap_err();
        assert!(matches!(err, CodegenError::Unsupported("more than one JOIN")));
    }

    #[test]
    fn generates_const_program_for_group_by_aggregate_query() {
        let src = generate("SELECT region, SUM(amount) FROM t GROUP BY region").unwrap();
        assert!(src.contains("const AGG_PARTS: &[AggPart] = &[AggPart::GroupKey, AggPart::Sum, ];"), "{src}");
        assert!(src.contains("const NUM_GROUP_KEYS: usize = 1;"), "{src}");
        assert!(src.contains("post_process(AGG_PARTS, NUM_GROUP_KEYS, ORDER_BY, LIMIT, rows)"));
    }

    #[test]
    fn generates_const_program_for_order_by_and_limit() {
        let src = generate("SELECT id FROM t ORDER BY id DESC LIMIT 10").unwrap();
        assert!(src.contains("const ORDER_BY: Option<(usize, bool)> = Some((0, true));"), "{src}");
        assert!(src.contains("const LIMIT: Option<usize> = Some(10);"), "{src}");
    }
}
